In [298]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Create array from height with correct units: np_height_m
#np_height_m = np.array(height) * 0.0254

# Create array from weight with correct units: np_weight_kg


# Calculate the BMI: bmi


# Print out bmi


In [299]:
bat = np.array([4,3,4,5,6,7,8,])

In [300]:
bat

array([4, 3, 4, 5, 6, 7, 8])

In [301]:
bat1 = np.array(bat)*3

In [302]:
bat1

array([12,  9, 12, 15, 18, 21, 24])

In [303]:
bat1[1]

9

In [304]:
i = 0
while i < len(bat1):
    print ("hello")
    i = i+1

hello
hello
hello
hello
hello
hello
hello


In [305]:
bat1 = np.append(bat1,bat)

In [306]:
bat1

array([12,  9, 12, 15, 18, 21, 24,  4,  3,  4,  5,  6,  7,  8])

In [307]:

arr1 = [2,3,4,5,1,2]

In [308]:
arr = [2,5,3,2,8]

In [309]:
arr1

[2, 3, 4, 5, 1, 2]

In [ ]:
arr

In [ ]:
for i in arr1:
    arr.append(arr1[i])

In [ ]:
arr

In [ ]:
arr2 = []

In [ ]:
for i in arr1:
    arr2.append(arr1[i])

In [ ]:
arr2

In [348]:
class Prime:
    def __init__(self,number):
        if number < 2: 
            print("There is no prime number less than 2")
        else:
            self.num = number
    def square_root(self):
        import math as m
        sqroot = [a+1 for a in range(int(m.sqrt(self.num)))]
        sqroot.remove(1)
        return sqroot
    
    def odds_w_two(self):
        x = [2]
        for i in range(self.num):
            if i % 2 != 0 and i>1:
                x.append(i)
        return x
    def prime(self):
        b = list(self.odds_w_two())
        b_copy = b
        for j in self.square_root():
            for i in b_copy:
                if (len(str(i)) >1 or i>3 )and i%j==0 :
                    b_copy.remove(i)
        return b_copy
              

In [349]:
primes = Prime(80)

In [350]:
z = primes.odds_w_two()

In [355]:
primes.prime()

[2, 3, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79]

In [359]:
s = Prime(40)

In [360]:
s.prime()

[2, 3, 7, 11, 13, 17, 19, 23, 29, 31, 37]

In [352]:
z

[2,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79]

In [270]:
m =primes.square_root()

In [271]:
for num in primes.odds_w_two():
    print(num)

2
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79


In [272]:
m

[2, 3, 4, 5, 6, 7, 8]

In [273]:
x = primes.odds_w_two()
x

[2,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79]

In [353]:
primes.prime()

[2, 3, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79]

In [218]:
from math import *
squareroot = [a+1 for a in range(int(sqrt(80)))]

In [134]:
squareroot.remove(1)
squareroot

[2, 3, 4, 5, 6, 7, 8]

In [135]:
x

[2,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79]

In [161]:
b = x
for j in squareroot:
    for i in x:
        if (len(str(i)) >1 or i>3 )and i%j==0 :
            b.remove(i)
print(b)

[2, 3, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79]


In [137]:
b

[2, 3, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79]

In [29]:
c = [a for a in b if a%5 !=0]

In [30]:
c

[2, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 49, 53, 59]

In [1]:
import math as m

In [3]:
print(int(m.sqrt(80)))


8


In [4]:
a = m.sqrt(80)
print(a)

8.94427190999916


In [31]:
class Myroot:
    def __init__(self, number):
        self.num = number
        
    def myroot(self):
        roots= [a+1 for a in range(int(m.sqrt(self.num)))]
        roots.remove(1)
       
        return roots


In [33]:
myroot_test=Myroot(100)

myroot_test.myroot()

[2, 3, 4, 5, 6, 7, 8, 9, 10]